// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OM_79_HUB.Data;

#nullable disable

namespace OM79HUB.Migrations
{
    [DbContext(typeof(OM_79_HUBContext))]
    [Migration("20230320175529_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OM_79_HUB.Models.CENTRAL79HUB", b =>
                {
                    b.Property<int>("OM79Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OM79Id"));

                    b.Property<string>("CBOX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USERID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OM79Id");

                    b.ToTable("CENTRAL79HUB");
                });
#pragma warning restore 612, 618
        }
    }
}
